---
# tasks file for ssh_check
- name: "Set sshd_port fact to configured ansible_port value"
  set_fact:
    sshd_port: "{{ansible_port}}"

- name: "Test connection for configured SSH port"
  local_action:
    module: "wait_for"
    host: "{{inventory_hostname}}"
    port: "{{ansible_port}}"
    state: "started"
    connect_timeout: 1
    timeout: 2
  ignore_errors: True
  register: configured_ssh

- name: "Set ansible_port to default SSH port and"
  set_fact:
    ansible_port: 22
  when:
  - configured_ssh|failed

- name: "Gather facts"
  setup:

